import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

interface BlogPostDraft {
  title: string
  description: string
  content: string
  slug: string
  imagePath: string
}

export async function sendBlogApprovalEmail(post: BlogPostDraft): Promise<boolean> {
  const approvalUrl = `${process.env.NEXT_PUBLIC_BASE_URL || 'https://wiebe-consulting.com'}/api/blog/approve?slug=${post.slug}&action=approve`
  const rejectUrl = `${process.env.NEXT_PUBLIC_BASE_URL || 'https://wiebe-consulting.com'}/api/blog/approve?slug=${post.slug}&action=reject`
  const previewUrl = `${process.env.NEXT_PUBLIC_BASE_URL || 'https://wiebe-consulting.com'}/blog/preview/${post.slug}`

  const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); padding: 30px; border-radius: 10px; margin-bottom: 20px; }
    .header h1 { color: #22d3ee; margin: 0 0 10px 0; font-size: 24px; }
    .header p { color: #94a3b8; margin: 0; }
    .content { background: #f8fafc; padding: 20px; border-radius: 10px; margin-bottom: 20px; }
    .post-title { color: #0f172a; font-size: 20px; font-weight: bold; margin-bottom: 10px; }
    .post-description { color: #64748b; margin-bottom: 20px; }
    .post-preview { background: white; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; max-height: 300px; overflow: hidden; }
    .buttons { display: flex; gap: 10px; margin-top: 20px; }
    .btn { display: inline-block; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; text-align: center; }
    .btn-approve { background: #22c55e; color: white; }
    .btn-reject { background: #ef4444; color: white; }
    .btn-preview { background: #3b82f6; color: white; }
    .footer { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 30px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>📝 New Blog Post Ready for Review</h1>
    <p>A new blog post has been generated and is waiting for your approval.</p>
  </div>

  <div class="content">
    <div class="post-title">${post.title}</div>
    <div class="post-description">${post.description}</div>

    <div class="post-preview">
      <strong>Preview:</strong><br><br>
      ${post.content.substring(0, 500)}...
    </div>

    <div class="buttons">
      <a href="${approvalUrl}" class="btn btn-approve">✅ Approve & Publish</a>
      <a href="${rejectUrl}" class="btn btn-reject">❌ Reject</a>
      <a href="${previewUrl}" class="btn btn-preview">👁️ Full Preview</a>
    </div>
  </div>

  <div class="footer">
    <p>This email was automatically generated by your Wiebe Consulting blog system.</p>
    <p>The post will NOT be published until you approve it.</p>
  </div>
</body>
</html>
`

  try {
    await resend.emails.send({
      from: process.env.EMAIL_FROM || 'Wiebe Consulting <blog@wiebe-consulting.com>',
      to: process.env.EMAIL_REPLY_TO || 'ben@wiebe-consulting.com',
      subject: `📝 Blog Review: ${post.title}`,
      html: emailHtml,
    })
    return true
  } catch (error) {
    console.error('Error sending approval email:', error)
    return false
  }
}

export async function sendBlogPublishedEmail(
  title: string,
  url: string
): Promise<boolean> {
  const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%); padding: 30px; border-radius: 10px; margin-bottom: 20px; }
    .header h1 { color: white; margin: 0 0 10px 0; font-size: 24px; }
    .header p { color: #dcfce7; margin: 0; }
    .content { background: #f8fafc; padding: 20px; border-radius: 10px; }
    .btn { display: inline-block; padding: 12px 24px; background: #0f172a; color: white; border-radius: 6px; text-decoration: none; font-weight: bold; }
  </style>
</head>
<body>
  <div class="header">
    <h1>✅ Blog Post Published!</h1>
    <p>Your blog post is now live on your website.</p>
  </div>

  <div class="content">
    <h2>${title}</h2>
    <p>Your blog post has been published and is now live.</p>
    <p><a href="${url}" class="btn">View Post →</a></p>

    <h3>Next Steps:</h3>
    <ul>
      <li>Share on LinkedIn</li>
      <li>Send to your email list</li>
      <li>Create 2-3 social posts from key points</li>
    </ul>
  </div>
</body>
</html>
`

  try {
    await resend.emails.send({
      from: process.env.EMAIL_FROM || 'Wiebe Consulting <blog@wiebe-consulting.com>',
      to: process.env.EMAIL_REPLY_TO || 'ben@wiebe-consulting.com',
      subject: `✅ Published: ${title}`,
      html: emailHtml,
    })
    return true
  } catch (error) {
    console.error('Error sending published email:', error)
    return false
  }
}
